import Login from '../components/Login'
import { useSession } from 'next-auth/react';
import { Inter } from "next/font/google";
import Head from 'next/head';
import Side_bar from '../components/Side_bar'
import Feed from '@/components/Feed';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession() // Session creation

  if (!session) return <Login /> // Session check
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>

      <main className='relative max-w-[1400px] mx-auto'>
        <Side_bar />
        <Feed />
        <div className='flex gap-6'>
        </div>
      </main>

    </div>
  );
}
